In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data
y = iris.target

# One hot encoding

In [6]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [7]:
y = to_categorical(y)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.preprocessing import MinMaxScaler

# Normalization Scaler

In [15]:
scaled_object = MinMaxScaler()

In [16]:
scaled_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaled_object.transform(X_train)
scaled_X_test = scaled_object.transform(X_test)

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
model = Sequential()

# Input layer
model.add(Dense(
    8,                   #neurons
    input_dim=4,         #4 features
    activation='relu')
)

# Hidden Layer
model.add(Dense(
    8,                   #neurons
    input_dim=4,         #4 features
    activation='relu')
)

# Output Layer
model.add(Dense(
    3,                   #neurons
    input_dim=4,         #4 features
    activation='softmax')
)

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 1s - loss: 1.0924 - accuracy: 0.3500
Epoch 2/150
 - 0s - loss: 1.0815 - accuracy: 0.3500
Epoch 3/150
 - 0s - loss: 1.0708 - accuracy: 0.3500
Epoch 4/150
 - 0s - loss: 1.0606 - accuracy: 0.3500
Epoch 5/150
 - 0s - loss: 1.0502 - accuracy: 0.3500
Epoch 6/150
 - 0s - loss: 1.0414 - accuracy: 0.3500
Epoch 7/150
 - 0s - loss: 1.0327 - accuracy: 0.3500
Epoch 8/150
 - 0s - loss: 1.0236 - accuracy: 0.3500
Epoch 9/150
 - 0s - loss: 1.0134 - accuracy: 0.3500
Epoch 10/150
 - 0s - loss: 1.0039 - accuracy: 0.3400
Epoch 11/150
 - 0s - loss: 0.9933 - accuracy: 0.3500
Epoch 12/150
 - 0s - loss: 0.9827 - accuracy: 0.3300
Epoch 13/150
 - 0s - loss: 0.9723 - accuracy: 0.3200
Epoch 14/150
 - 0s - loss: 0.9621 - accuracy: 0.3300
Epoch 15/150
 - 0s - loss: 0.9522 - accuracy: 0.3600
Epoch 16/150
 - 0s - loss: 0.9426 - accuracy: 0.3500
Epoch 17/150
 - 0s - loss: 0.9331 - accuracy: 0.3800
Epoch 18/150
 - 0s - loss: 0.9245 - accuracy: 0.4500
Epoch 1

Epoch 150/150
 - 0s - loss: 0.3789 - accuracy: 0.9300


In [29]:
model.predict(scaled_X_test)

array([[1.4921938e-02, 5.6344610e-01, 4.2163202e-01],
       [9.3428534e-01, 6.0828246e-02, 4.8864051e-03],
       [1.4858154e-05, 1.4188263e-01, 8.5810256e-01],
       [9.3024923e-03, 5.2478075e-01, 4.6591672e-01],
       [6.5835807e-03, 5.0608623e-01, 4.8733014e-01],
       [9.1870999e-01, 7.3936582e-02, 7.3534441e-03],
       [5.5780187e-02, 6.2146521e-01, 3.2275462e-01],
       [4.2120568e-04, 3.1394446e-01, 6.8563437e-01],
       [1.5842872e-03, 3.4848222e-01, 6.4993352e-01],
       [3.3272244e-02, 5.9179109e-01, 3.7493673e-01],
       [1.5912374e-03, 4.1597462e-01, 5.8243418e-01],
       [9.0337217e-01, 8.6290747e-02, 1.0337043e-02],
       [9.2466146e-01, 6.8785012e-02, 6.5535614e-03],
       [9.0947914e-01, 8.1345722e-02, 9.1751739e-03],
       [9.3833625e-01, 5.7132643e-02, 4.5310953e-03],
       [1.3188603e-02, 5.8270204e-01, 4.0410933e-01],
       [1.7668138e-04, 2.6449800e-01, 7.3532528e-01],
       [2.9126156e-02, 5.7063949e-01, 4.0023434e-01],
       [1.4270989e-02, 5.510

In [30]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [32]:
y_pred = model.predict_classes(scaled_X_test)
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test.argmax(axis=1), y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [34]:
model.save('my_model.h5')    # save all the weights of the model

In [36]:
from keras.models import load_model
new_model = load_model('my_model.h5')